### ISSUE TITLE
setup.py depends on installed numpy

### ISSUE THREAD

**Issue by passionsfrucht** [InvestmentSystems/arraykit#60]
On a freshly installed python system, `numpy` is often not installed and by installing via `pip` setup would fail.

This leads to the following build errors (according to my probably too short analysis):

```
 Collecting arraykit==0.1.8
  Using cached arraykit-0.1.8.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /builds/eego_device_test/eego_test_bench/.nox/mypy-3-9/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q6dm9724/arraykit_3bd51a2a837743e683e9b5b25237b101/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q6dm9724/arraykit_3bd51a2a837743e683e9b5b25237b101/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1evc_wph
         cwd: /tmp/pip-install-q6dm9724/arraykit_3bd51a2a837743e683e9b5b25237b101/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q6dm9724/arraykit_3bd51a2a837743e683e9b5b25237b101/setup.py", line 3, in <module>
        from numpy.distutils.misc_util import get_info
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
```

**Comment by flexatone** [comment]
Many thanks for isolating this issue. We were not seeing it due to a two-stage requirement reading process. I will explore some alternatives.

https://stackoverflow.com/questions/54117786/add-numpy-get-include-argument-to-setuptools-without-preinstalled-numpy
